In [18]:
import tensorflow as ts
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [19]:
# Load the trained model , scaler pickle,onehot
model = load_model('model.h5')

## Load the encoder and sclaer

with open('onehot_encoder_gro.pkl','rb') as file:
    label_encoder_geo = pickle.load(file)


with open('label_encoder_gender.pkl','rb') as file:
    label_encoder_gender = pickle.load(file)


with open('scaler.pkl','rb') as file:
    scaler = pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
s:\Mechine Learning\sec_53\ANN\Lib\site-packages\sklearn\base.py:525: InconsistentVersionWarning: Trying to unpickle estimator OneHotEncoder from version 1.6.1 when using version 1.9.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
s:\Mechine Learning\sec_53\ANN\Lib\site-packages\sklearn\base.py:525: InconsistentVersionWarning: Trying to unpickle estimator LabelEncoder from version 1.6.1 when using version 1.9.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
s:\Mechine Learning\sec_53\ANN\Lib\site-packages\sklearn\base.py:525: InconsistentVersionWarning: Trying to unpickle estimator StandardScaler from version 1.6.1 when using version 1.9.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [20]:
# Example input data
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [21]:
geo_encoded = label_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded,columns=label_encoder_geo.get_feature_names_out(['Geography']))

s:\Mechine Learning\sec_53\ANN\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [22]:
geo_encoded_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [39]:
input_df = pd.DataFrame([input_data])

In [40]:
## Encode categorical variable
input_df['Gender'] =label_encoder_gender.transform(input_df['Gender'])

In [41]:
## Concationate the geographicaal data
input_df = pd.concat([input_df.drop('Geography',axis=1),geo_encoded_df],axis=1)

In [42]:
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [45]:
## Scaling Data
input_scaled = scaler.transform(input_df)

In [46]:
# Prediction
Prediction  = model.predict(input_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 388ms/step

In [47]:
Prediction

array([[0.02337901]], dtype=float32)

In [48]:
Prediction_prob = Prediction[0][0]

Prediction_prob

np.float32(0.023379013)

In [49]:
if Prediction_prob > 0.5:
    print('This customer is likely to churn')
else:
    print('This customer is not likely to churn')

This customer is not likely to churn